package book.course.molareza.ir.mp3player.db;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteDatabase.CursorFactory;
import android.database.sqlite.SQLiteOpenHelper;
import android.util.Log;
import de.greenrobot.dao.AbstractDaoMaster;
import de.greenrobot.dao.identityscope.IdentityScopeType;

import book.course.molareza.ir.mp3player.db.FavoriteDetailDao;
import book.course.molareza.ir.mp3player.db.FavoriteMusicIraniDao;
import book.course.molareza.ir.mp3player.db.FavoriteMusicKharejiDao;
import book.course.molareza.ir.mp3player.db.FavoriteClipDao;
import book.course.molareza.ir.mp3player.db.LikeDetailDao;
import book.course.molareza.ir.mp3player.db.LikeMusicIraniDao;
import book.course.molareza.ir.mp3player.db.LikeMusicKharejiDao;
import book.course.molareza.ir.mp3player.db.LikeClipDao;
import book.course.molareza.ir.mp3player.db.LikeOtherAppDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * Master of DAO (schema version 7): knows all DAOs.
*/
public class DaoMaster extends AbstractDaoMaster {
    public static final int SCHEMA_VERSION = 7;

    /** Creates underlying database table using DAOs. */
    public static void createAllTables(SQLiteDatabase db, boolean ifNotExists) {
        FavoriteDetailDao.createTable(db, ifNotExists);
        FavoriteMusicIraniDao.createTable(db, ifNotExists);
        FavoriteMusicKharejiDao.createTable(db, ifNotExists);
        FavoriteClipDao.createTable(db, ifNotExists);
        LikeDetailDao.createTable(db, ifNotExists);
        LikeMusicIraniDao.createTable(db, ifNotExists);
        LikeMusicKharejiDao.createTable(db, ifNotExists);
        LikeClipDao.createTable(db, ifNotExists);
        LikeOtherAppDao.createTable(db, ifNotExists);
    }
    
    /** Drops underlying database table using DAOs. */
    public static void dropAllTables(SQLiteDatabase db, boolean ifExists) {
        FavoriteDetailDao.dropTable(db, ifExists);
        FavoriteMusicIraniDao.dropTable(db, ifExists);
        FavoriteMusicKharejiDao.dropTable(db, ifExists);
        FavoriteClipDao.dropTable(db, ifExists);
        LikeDetailDao.dropTable(db, ifExists);
        LikeMusicIraniDao.dropTable(db, ifExists);
        LikeMusicKharejiDao.dropTable(db, ifExists);
        LikeClipDao.dropTable(db, ifExists);
        LikeOtherAppDao.dropTable(db, ifExists);
    }
    
    public static abstract class OpenHelper extends SQLiteOpenHelper {

        public OpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory, SCHEMA_VERSION);
        }

        @Override
        public void onCreate(SQLiteDatabase db) {
            Log.i("greenDAO", "Creating tables for schema version " + SCHEMA_VERSION);
            createAllTables(db, false);
        }
    }
    
    /** WARNING: Drops all table on Upgrade! Use only during development. */
    public static class DevOpenHelper extends OpenHelper {
        public DevOpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory);
        }

        @Override
        public void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion) {
            Log.i("greenDAO", "Upgrading schema from version " + oldVersion + " to " + newVersion + " by dropping all tables");
            dropAllTables(db, true);
            onCreate(db);
        }
    }

    public DaoMaster(SQLiteDatabase db) {
        super(db, SCHEMA_VERSION);
        registerDaoClass(FavoriteDetailDao.class);
        registerDaoClass(FavoriteMusicIraniDao.class);
        registerDaoClass(FavoriteMusicKharejiDao.class);
        registerDaoClass(FavoriteClipDao.class);
        registerDaoClass(LikeDetailDao.class);
        registerDaoClass(LikeMusicIraniDao.class);
        registerDaoClass(LikeMusicKharejiDao.class);
        registerDaoClass(LikeClipDao.class);
        registerDaoClass(LikeOtherAppDao.class);
    }
    
    public DaoSession newSession() {
        return new DaoSession(db, IdentityScopeType.Session, daoConfigMap);
    }
    
    public DaoSession newSession(IdentityScopeType type) {
        return new DaoSession(db, type, daoConfigMap);
    }
    
}
