package book.course.molareza.ir.mp3player.db;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import book.course.molareza.ir.mp3player.db.FavoriteDetail;
import book.course.molareza.ir.mp3player.db.FavoriteMusicIrani;
import book.course.molareza.ir.mp3player.db.FavoriteMusicKhareji;
import book.course.molareza.ir.mp3player.db.FavoriteClip;
import book.course.molareza.ir.mp3player.db.ListDownload;
import book.course.molareza.ir.mp3player.db.LikeDetail;
import book.course.molareza.ir.mp3player.db.LikeMusicIrani;
import book.course.molareza.ir.mp3player.db.LikeMusicKhareji;
import book.course.molareza.ir.mp3player.db.LikeClip;
import book.course.molareza.ir.mp3player.db.LikeOtherApp;

import book.course.molareza.ir.mp3player.db.FavoriteDetailDao;
import book.course.molareza.ir.mp3player.db.FavoriteMusicIraniDao;
import book.course.molareza.ir.mp3player.db.FavoriteMusicKharejiDao;
import book.course.molareza.ir.mp3player.db.FavoriteClipDao;
import book.course.molareza.ir.mp3player.db.ListDownloadDao;
import book.course.molareza.ir.mp3player.db.LikeDetailDao;
import book.course.molareza.ir.mp3player.db.LikeMusicIraniDao;
import book.course.molareza.ir.mp3player.db.LikeMusicKharejiDao;
import book.course.molareza.ir.mp3player.db.LikeClipDao;
import book.course.molareza.ir.mp3player.db.LikeOtherAppDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig favoriteDetailDaoConfig;
    private final DaoConfig favoriteMusicIraniDaoConfig;
    private final DaoConfig favoriteMusicKharejiDaoConfig;
    private final DaoConfig favoriteClipDaoConfig;
    private final DaoConfig listDownloadDaoConfig;
    private final DaoConfig likeDetailDaoConfig;
    private final DaoConfig likeMusicIraniDaoConfig;
    private final DaoConfig likeMusicKharejiDaoConfig;
    private final DaoConfig likeClipDaoConfig;
    private final DaoConfig likeOtherAppDaoConfig;

    private final FavoriteDetailDao favoriteDetailDao;
    private final FavoriteMusicIraniDao favoriteMusicIraniDao;
    private final FavoriteMusicKharejiDao favoriteMusicKharejiDao;
    private final FavoriteClipDao favoriteClipDao;
    private final ListDownloadDao listDownloadDao;
    private final LikeDetailDao likeDetailDao;
    private final LikeMusicIraniDao likeMusicIraniDao;
    private final LikeMusicKharejiDao likeMusicKharejiDao;
    private final LikeClipDao likeClipDao;
    private final LikeOtherAppDao likeOtherAppDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        favoriteDetailDaoConfig = daoConfigMap.get(FavoriteDetailDao.class).clone();
        favoriteDetailDaoConfig.initIdentityScope(type);

        favoriteMusicIraniDaoConfig = daoConfigMap.get(FavoriteMusicIraniDao.class).clone();
        favoriteMusicIraniDaoConfig.initIdentityScope(type);

        favoriteMusicKharejiDaoConfig = daoConfigMap.get(FavoriteMusicKharejiDao.class).clone();
        favoriteMusicKharejiDaoConfig.initIdentityScope(type);

        favoriteClipDaoConfig = daoConfigMap.get(FavoriteClipDao.class).clone();
        favoriteClipDaoConfig.initIdentityScope(type);

        listDownloadDaoConfig = daoConfigMap.get(ListDownloadDao.class).clone();
        listDownloadDaoConfig.initIdentityScope(type);

        likeDetailDaoConfig = daoConfigMap.get(LikeDetailDao.class).clone();
        likeDetailDaoConfig.initIdentityScope(type);

        likeMusicIraniDaoConfig = daoConfigMap.get(LikeMusicIraniDao.class).clone();
        likeMusicIraniDaoConfig.initIdentityScope(type);

        likeMusicKharejiDaoConfig = daoConfigMap.get(LikeMusicKharejiDao.class).clone();
        likeMusicKharejiDaoConfig.initIdentityScope(type);

        likeClipDaoConfig = daoConfigMap.get(LikeClipDao.class).clone();
        likeClipDaoConfig.initIdentityScope(type);

        likeOtherAppDaoConfig = daoConfigMap.get(LikeOtherAppDao.class).clone();
        likeOtherAppDaoConfig.initIdentityScope(type);

        favoriteDetailDao = new FavoriteDetailDao(favoriteDetailDaoConfig, this);
        favoriteMusicIraniDao = new FavoriteMusicIraniDao(favoriteMusicIraniDaoConfig, this);
        favoriteMusicKharejiDao = new FavoriteMusicKharejiDao(favoriteMusicKharejiDaoConfig, this);
        favoriteClipDao = new FavoriteClipDao(favoriteClipDaoConfig, this);
        listDownloadDao = new ListDownloadDao(listDownloadDaoConfig, this);
        likeDetailDao = new LikeDetailDao(likeDetailDaoConfig, this);
        likeMusicIraniDao = new LikeMusicIraniDao(likeMusicIraniDaoConfig, this);
        likeMusicKharejiDao = new LikeMusicKharejiDao(likeMusicKharejiDaoConfig, this);
        likeClipDao = new LikeClipDao(likeClipDaoConfig, this);
        likeOtherAppDao = new LikeOtherAppDao(likeOtherAppDaoConfig, this);

        registerDao(FavoriteDetail.class, favoriteDetailDao);
        registerDao(FavoriteMusicIrani.class, favoriteMusicIraniDao);
        registerDao(FavoriteMusicKhareji.class, favoriteMusicKharejiDao);
        registerDao(FavoriteClip.class, favoriteClipDao);
        registerDao(ListDownload.class, listDownloadDao);
        registerDao(LikeDetail.class, likeDetailDao);
        registerDao(LikeMusicIrani.class, likeMusicIraniDao);
        registerDao(LikeMusicKhareji.class, likeMusicKharejiDao);
        registerDao(LikeClip.class, likeClipDao);
        registerDao(LikeOtherApp.class, likeOtherAppDao);
    }
    
    public void clear() {
        favoriteDetailDaoConfig.getIdentityScope().clear();
        favoriteMusicIraniDaoConfig.getIdentityScope().clear();
        favoriteMusicKharejiDaoConfig.getIdentityScope().clear();
        favoriteClipDaoConfig.getIdentityScope().clear();
        listDownloadDaoConfig.getIdentityScope().clear();
        likeDetailDaoConfig.getIdentityScope().clear();
        likeMusicIraniDaoConfig.getIdentityScope().clear();
        likeMusicKharejiDaoConfig.getIdentityScope().clear();
        likeClipDaoConfig.getIdentityScope().clear();
        likeOtherAppDaoConfig.getIdentityScope().clear();
    }

    public FavoriteDetailDao getFavoriteDetailDao() {
        return favoriteDetailDao;
    }

    public FavoriteMusicIraniDao getFavoriteMusicIraniDao() {
        return favoriteMusicIraniDao;
    }

    public FavoriteMusicKharejiDao getFavoriteMusicKharejiDao() {
        return favoriteMusicKharejiDao;
    }

    public FavoriteClipDao getFavoriteClipDao() {
        return favoriteClipDao;
    }

    public ListDownloadDao getListDownloadDao() {
        return listDownloadDao;
    }

    public LikeDetailDao getLikeDetailDao() {
        return likeDetailDao;
    }

    public LikeMusicIraniDao getLikeMusicIraniDao() {
        return likeMusicIraniDao;
    }

    public LikeMusicKharejiDao getLikeMusicKharejiDao() {
        return likeMusicKharejiDao;
    }

    public LikeClipDao getLikeClipDao() {
        return likeClipDao;
    }

    public LikeOtherAppDao getLikeOtherAppDao() {
        return likeOtherAppDao;
    }

}
