package book.course.molareza.ir.mp3player.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import book.course.molareza.ir.mp3player.db.FavoriteMusicKhareji;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "FAVORITE_MUSIC_KHAREJI".
*/
public class FavoriteMusicKharejiDao extends AbstractDao<FavoriteMusicKhareji, Long> {

    public static final String TABLENAME = "FAVORITE_MUSIC_KHAREJI";

    /**
     * Properties of entity FavoriteMusicKhareji.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Name = new Property(1, String.class, "name", false, "NAME");
        public final static Property Id_item = new Property(2, String.class, "id_item", false, "ID_ITEM");
        public final static Property Album = new Property(3, String.class, "album", false, "ALBUM");
        public final static Property ThImage = new Property(4, String.class, "thImage", false, "TH_IMAGE");
        public final static Property BigImage = new Property(5, String.class, "bigImage", false, "BIG_IMAGE");
        public final static Property Mp3_64 = new Property(6, String.class, "mp3_64", false, "MP3_64");
        public final static Property Mp3_128 = new Property(7, String.class, "mp3_128", false, "MP3_128");
        public final static Property Table = new Property(8, String.class, "table", false, "TABLE");
    };


    public FavoriteMusicKharejiDao(DaoConfig config) {
        super(config);
    }
    
    public FavoriteMusicKharejiDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"FAVORITE_MUSIC_KHAREJI\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"NAME\" TEXT," + // 1: name
                "\"ID_ITEM\" TEXT," + // 2: id_item
                "\"ALBUM\" TEXT," + // 3: album
                "\"TH_IMAGE\" TEXT," + // 4: thImage
                "\"BIG_IMAGE\" TEXT," + // 5: bigImage
                "\"MP3_64\" TEXT," + // 6: mp3_64
                "\"MP3_128\" TEXT," + // 7: mp3_128
                "\"TABLE\" TEXT);"); // 8: table
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"FAVORITE_MUSIC_KHAREJI\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, FavoriteMusicKhareji entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
 
        String id_item = entity.getId_item();
        if (id_item != null) {
            stmt.bindString(3, id_item);
        }
 
        String album = entity.getAlbum();
        if (album != null) {
            stmt.bindString(4, album);
        }
 
        String thImage = entity.getThImage();
        if (thImage != null) {
            stmt.bindString(5, thImage);
        }
 
        String bigImage = entity.getBigImage();
        if (bigImage != null) {
            stmt.bindString(6, bigImage);
        }
 
        String mp3_64 = entity.getMp3_64();
        if (mp3_64 != null) {
            stmt.bindString(7, mp3_64);
        }
 
        String mp3_128 = entity.getMp3_128();
        if (mp3_128 != null) {
            stmt.bindString(8, mp3_128);
        }
 
        String table = entity.getTable();
        if (table != null) {
            stmt.bindString(9, table);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public FavoriteMusicKhareji readEntity(Cursor cursor, int offset) {
        FavoriteMusicKhareji entity = new FavoriteMusicKhareji( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // name
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // id_item
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // album
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // thImage
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // bigImage
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // mp3_64
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // mp3_128
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8) // table
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, FavoriteMusicKhareji entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setId_item(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setAlbum(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setThImage(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setBigImage(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setMp3_64(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setMp3_128(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setTable(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(FavoriteMusicKhareji entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(FavoriteMusicKhareji entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
