package book.course.molareza.ir.mp3player.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "FAVORITE_CLIP".
 */
public class FavoriteClip {

    private Long id;
    private String id_item;
    private String name;
    private String album;
    private String thImage;
    private String bigImage;
    private String clip;

    public FavoriteClip() {
    }

    public FavoriteClip(Long id) {
        this.id = id;
    }

    public FavoriteClip(Long id, String id_item, String name, String album, String thImage, String bigImage, String clip) {
        this.id = id;
        this.id_item = id_item;
        this.name = name;
        this.album = album;
        this.thImage = thImage;
        this.bigImage = bigImage;
        this.clip = clip;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getId_item() {
        return id_item;
    }

    public void setId_item(String id_item) {
        this.id_item = id_item;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getAlbum() {
        return album;
    }

    public void setAlbum(String album) {
        this.album = album;
    }

    public String getThImage() {
        return thImage;
    }

    public void setThImage(String thImage) {
        this.thImage = thImage;
    }

    public String getBigImage() {
        return bigImage;
    }

    public void setBigImage(String bigImage) {
        this.bigImage = bigImage;
    }

    public String getClip() {
        return clip;
    }

    public void setClip(String clip) {
        this.clip = clip;
    }

}
