package book.course.molareza.ir.mp3player.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "FAVORITE_DETAIL".
 */
public class FavoriteDetail {

    private Long id;
    private String name;
    private String id_item;
    private String album;
    private String thImage;
    private String bigImage;
    private String text;

    public FavoriteDetail() {
    }

    public FavoriteDetail(Long id) {
        this.id = id;
    }

    public FavoriteDetail(Long id, String name, String id_item, String album, String thImage, String bigImage, String text) {
        this.id = id;
        this.name = name;
        this.id_item = id_item;
        this.album = album;
        this.thImage = thImage;
        this.bigImage = bigImage;
        this.text = text;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getId_item() {
        return id_item;
    }

    public void setId_item(String id_item) {
        this.id_item = id_item;
    }

    public String getAlbum() {
        return album;
    }

    public void setAlbum(String album) {
        this.album = album;
    }

    public String getThImage() {
        return thImage;
    }

    public void setThImage(String thImage) {
        this.thImage = thImage;
    }

    public String getBigImage() {
        return bigImage;
    }

    public void setBigImage(String bigImage) {
        this.bigImage = bigImage;
    }

    public String getText() {
        return text;
    }

    public void setText(String text) {
        this.text = text;
    }

}
