package book.course.molareza.ir.mp3player.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "LIST_DOWNLOAD".
 */
public class ListDownload {

    private Long id;
    private String name;
    private String album;
    private String mp3;
    private String image;
    private String type;

    public ListDownload() {
    }

    public ListDownload(Long id) {
        this.id = id;
    }

    public ListDownload(Long id, String name, String album, String mp3, String image, String type) {
        this.id = id;
        this.name = name;
        this.album = album;
        this.mp3 = mp3;
        this.image = image;
        this.type = type;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getAlbum() {
        return album;
    }

    public void setAlbum(String album) {
        this.album = album;
    }

    public String getMp3() {
        return mp3;
    }

    public void setMp3(String mp3) {
        this.mp3 = mp3;
    }

    public String getImage() {
        return image;
    }

    public void setImage(String image) {
        this.image = image;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

}
